# -*- coding: utf-8 -*-
"""
/******************************************************************************
        grd2stream – generates streamlines from velocity grids using GMT6
                                 A QGIS plugin
        This plugin utilizes the CLI tool 'grd2stream' by Thomas Kleiner
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-01
        copyright            : (C) 2013-2025 by Thomas Kleiner & SFP-Team
        email                : scienceflightplanner@gmail.com
        git sha              : $Format:%H$
 ******************************************************************************/

/******************************************************************************
 *                                                                            *
 *    This program is free software; you can redistribute it and/or modify    *
 *    it under the terms of the GNU General Public License as published by    *
 *    the Free Software Foundation; either version 3 of the License, or       *
 *    (at your option) any later version.                                     *
 *                                                                            *
 ******************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'grd_2_stream_dialog_base.ui'))


class Grd2StreamDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(Grd2StreamDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
