name: Cross-compile grd2stream for macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cross-compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            clang \
            make \
            automake \
            autoconf \
            libtool \
            pkg-config \
            libgmp-dev \
            libmpfr-dev \
            libmpc-dev \
            zlib1g-dev \
            libssl-dev \
            libncurses5-dev \
            libncursesw5-dev

      - name: Set up osxcross
        run: |
          git clone https://github.com/tpoechtrager/osxcross.git
          cd osxcross
          wget -O tarballs/MacOSX11.3.sdk.tar.xz https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz
          ./build.sh
          export PATH="$PATH:$(pwd)/target/bin"

      - name: Bootstrap grd2stream
        run: |
          cd $GITHUB_WORKSPACE
          ./bootstrap.sh

      - name: Configure and build grd2stream
        run: |
          cd $GITHUB_WORKSPACE
          export CC="o64-clang"
          export CXX="o64-clang++"
          export CPPFLAGS="-target arm64-apple-macos11"
          export LDFLAGS="-target arm64-apple-macos11"
          ./configure --host=aarch64-apple-darwin20 --enable-gmt-api
          make

      - name: Verify the binary
        run: |
          cd $GITHUB_WORKSPACE
          file src/grd2stream

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: grd2stream-macos-arm
          path: src/grd2stream