name: Test grd2stream on MacOS ARM

on:
  push:
    paths:
      - "install_grd2stream.py"
  workflow_dispatch:

jobs:
  test-macos-arm:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run installation script
        run: |
          python3 test_install_macos.py
