name: Test grd2stream Binary on macOS

on:
  workflow_run:
    workflows: ["Cross-Compile grd2stream for macOS"]
    types:
      - completed
  workflow_dispatch:

jobs:
  test-binary:
    runs-on: macos-latest

    steps:
      - name: Download binary artifact
        uses: actions/download-artifact@v3
        with:
          name: grd2stream-macos-arm
          path: ./src

      - name: Set Binary Permissions
        run: |
          echo "Setting executable permissions for the binary..."
          chmod +x ./src/grd2stream

      - name: Set up Environment
        run: |
          echo "Installing dependencies..."
          brew install --cask qgis
          brew install gmt

      - name: Debug Paths
        run: |
          echo "Current Dir: $(pwd)"
          echo "Files in src folder:"
          ls -lah ./src

      - name: Test grd2stream Binary
        run: |
          # Define paths
          BINARY_PATH="./src/grd2stream"
          RASTER_PATH_1="./smaller_topleft_vx.tif"
          RASTER_PATH_2="./smaller_topleft_vy.tif"
          COORDINATES="-192020.2232552988 -1125747.9813301556"

          echo "Checking if the binary exists..."
          if [ ! -f "$BINARY_PATH" ]; then
            echo "Binary not found at $BINARY_PATH"
            exit 1
          fi

          echo "Running the binary with provided inputs..."
          echo "$COORDINATES" | "$BINARY_PATH" "$RASTER_PATH_1" "$RASTER_PATH_2" || echo "Failed to execute grd2stream"

      - name: Check Binary Dependencies
        run: |
          echo "Checking library dependencies for grd2stream..."
          otool -L ./src/grd2stream