name: Build & Test grd2stream on macOS

on:
  push:
    branches:
      - testing-ground
  pull_request:
    branches:
      - testing-ground
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MacPorts
        uses: melusina-org/setup-macports@v1
        id: 'macports'
        with:
          parameters: '.github/parameters/setup-macports.yaml'

      - name: Verify MacPorts installation
        run: |
          which port
          port version

      - name: Install dependencies
        run: |
          sudo port install autoconf autoconf-archive automake libtool
          sudo port install gdal +netcdf+hdf5
          sudo port install gmt6 +gdal

      - name: Find NetCDF installation path
        id: netcdf-path
        run: |
          if command -v nc-config &> /dev/null; then
            NETCDF_PREFIX=$(nc-config --prefix)
          elif command -v pkg-config &> /dev/null; then
            NETCDF_PREFIX=$(pkg-config --variable=prefix netcdf)
          else
            echo "Error: Neither nc-config nor pkg-config is available."
            exit 1
          fi
          echo "NetCDF prefix: $NETCDF_PREFIX"
          echo "NETCDF_PREFIX=$NETCDF_PREFIX" >> $GITHUB_ENV

      - name: Bootstrap grd2stream
        run: |
          chmod +x bootstrap.sh
          ./bootstrap.sh

      - name: Configure and build grd2stream
        run: |
          CC=clang CFLAGS="-arch x86_64 -arch arm64" ./configure --prefix=$HOME --enable-gmt-api --enable-debug --with-netcdf=$NETCDF_PREFIX
          make

      - name: Verify the binary
        run: |
          file src/grd2stream
          lipo -archs src/grd2stream

      - name: Add build folder to Git
        run: |
          git config --global user.name "klairvoyage"
          git config --global user.email "122225342+klairvoyage@users.noreply.github.com"
          git add .
          git commit -m "Add build folder & binary"
          git push

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: grd2stream-macos
          path: src/grd2stream

      - name: Install QGIS for testing
        run: |
          brew install --cask qgis

      - name: Test grd2stream Binary
        run: |
          # Define paths
          BINARY_PATH="./src/grd2stream"
          RASTER_PATH_1="./smaller_topleft_vx.tif"
          RASTER_PATH_2="./smaller_topleft_vy.tif"
          COORDINATES="-192020.2232552988 -1125747.9813301556"

          echo "Checking if the binary exists..."
          if [ ! -f "$BINARY_PATH" ]; then
            echo "Binary not found at $BINARY_PATH"
            exit 1
          fi

          echo "Running the binary with provided inputs..."
          echo "$COORDINATES" | "$BINARY_PATH" "$RASTER_PATH_1" "$RASTER_PATH_2" || echo "Failed to execute grd2stream"