name: Build & Test grd2stream on macOS

on:
  push:
    branches:
      - testing-ground
  pull_request:
    branches:
      - testing-ground
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install --cask qgis
          brew install gmt

      - name: Bootstrap grd2stream
        run: |
          chmod +x bootstrap.sh
          ./bootstrap.sh

      - name: Configure and build grd2stream
        run: |
          ./configure --enable-gmt-api
          make

      - name: Verify the binary
        run: |
          file src/grd2stream

      - name: Test grd2stream Binary
        run: |
          # Define paths
          BINARY_PATH="./src/grd2stream"
          RASTER_PATH_1="./smaller_topleft_vx.tif"
          RASTER_PATH_2="./smaller_topleft_vy.tif"
          COORDINATES="-192020.2232552988 -1125747.9813301556"

          echo "Checking if the binary exists..."
          if [ ! -f "$BINARY_PATH" ]; then
            echo "Binary not found at $BINARY_PATH"
            exit 1
          fi

          echo "Running the binary with provided inputs..."
          echo "$COORDINATES" | "$BINARY_PATH" "$RASTER_PATH_1" "$RASTER_PATH_2" || echo "Failed to execute grd2stream"

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: grd2stream-macos
          path: src/grd2stream