name: Build grd2stream on Windows x86_64

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Cache Miniconda
        id: cache-miniconda
        uses: actions/cache@v3
        with:
          path: $env:USERPROFILE\miniconda3
          key: miniconda-${{ runner.os }}-${{ hashFiles('environment.yml') }}
          restore-keys: |
            miniconda-${{ runner.os }}-

      - name: Install Miniconda (Windows x86_64)
        if: steps.cache-miniconda.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          wget "https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe" -outfile ".\miniconda.exe"
          Start-Process -FilePath ".\miniconda.exe" -ArgumentList "/S" -Wait
          del .\miniconda.exe

      - name: Initialize Conda
        shell: powershell
        run: |
          $env:Path = "$env:USERPROFILE\miniconda3\Scripts;$env:USERPROFILE\miniconda3\Library\bin;$env:Path"
          conda init powershell
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda create -y -n GMT6 gmt=6* gdal hdf5 netcdf4
          conda activate GMT6
          curl.exe -L https://github.com/tkleiner/grd2stream/releases/download/v0.2.14/grd2stream-0.2.14.tar.gz -o grd2stream-0.2.14.tar.gz
          tar xvfz grd2stream-0.2.14.tar.gz
          cd grd2stream-0.2.14
          ./configure --prefix="$env:CONDA_PREFIX" --enable-gmt-api
          make
          make install
          grd2stream -h